# Generated by Django 2.2.28 on 2022-04-20 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20220420_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image4',
        ),
    ]
