# Generated by Django 2.2.28 on 2022-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20220420_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='memory',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='ram',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.TextField(blank=True),
        ),
    ]
