# Generated by Django 2.2.28 on 2022-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20220420_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(null=True, upload_to='static/media/item-images'),
        ),
    ]
