# Generated by Django 2.2.28 on 2022-04-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20220420_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='port',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='webcam',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/item-images'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to='media/item-images'),
        ),
    ]
