# Generated by Django 2.2.28 on 2022-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='date_added',
            new_name='create_at',
        ),
        migrations.RenameField(
            model_name='productreview',
            old_name='stars',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='reviews',
        ),
        migrations.AddField(
            model_name='productreview',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
