# Generated by Django 2.2.28 on 2022-05-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20220426_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
